# Generated by Django 3.2 on 2023-08-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='date',
            field=models.DateField(default='2023-08-26', verbose_name='Date'),
        ),
    ]
